// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yxlwuoeiokjdnsrmfuxc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl4bHd1b2Vpb2tqZG5zcm1mdXhjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwNjUzNjMsImV4cCI6MjA2MDY0MTM2M30.DgNBrlAC5dY3HVfuPk-sOWwhn51PTDfyRsqb0MwQlJo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);